
version: '3.8'
services:

  mongocandidate:
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  #pull image from ECR and simply runs api calls imperatively 
  candidateapp:
  #IF Testing setup, uncomment this
    build:
      context: .
    ports:
      - 80:80
    depends_on: 
      - mongocandidate

  evaluationworker:
    image: '426691418260.dkr.ecr.us-east-1.amazonaws.com/deployment_testing'
    depends_on: 
      #- candidateapp
      - candidateapp
    volumes:
      - ./src:/app/src
    environment:
      - projectID=65f5bf2792973b834a7556bf
      - templateId=65ed04e7fbcd491e89a5433d
      - skill=python
