
name: Deploy with Preloaded DB Volume



on:

  push:

    branches:

      - main



permissions:

  id-token: write

  contents: read



jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v3



      - name: Configure AWS credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-region: us-east-1

          role-to-assume: arn:aws:iam::426691418260:role/PullDeploymentTesting

          role-session-name: GitHubActions



      - name: Login to Amazon ECR

        uses: aws-actions/amazon-ecr-login@v2



      - name: Build and Run with Docker Compose

        run: |

          docker-compose up --abort-on-container-exit

          

      - name: Cleanup

        if: always()

        run: docker-compose down
    
    
    